// Generated by gencpp from file OpenFace/My_message.msg
// DO NOT EDIT!


#ifndef OPENFACE_MESSAGE_MY_MESSAGE_H
#define OPENFACE_MESSAGE_MY_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace OpenFace
{
template <class ContainerAllocator>
struct My_message_
{
  typedef My_message_<ContainerAllocator> Type;

  My_message_()
    : pose_tra_x(0.0)
    , pose_tra_y(0.0)
    , pose_tra_z(0.0)
    , pose_rot_x(0.0)
    , pose_rot_y(0.0)
    , pose_rot_z(0.0)
    , gaze_0_rot_x(0.0)
    , gaze_0_rot_y(0.0)
    , gaze_0_rot_z(0.0)
    , gaze_1_rot_x(0.0)
    , gaze_1_rot_y(0.0)
    , gaze_1_rot_z(0.0)
    , diff_gaze_x(0.0)
    , diff_gaze_y(0.0)
    , diff_gaze_z(0.0)
    , id_model(0)  {
    }
  My_message_(const ContainerAllocator& _alloc)
    : pose_tra_x(0.0)
    , pose_tra_y(0.0)
    , pose_tra_z(0.0)
    , pose_rot_x(0.0)
    , pose_rot_y(0.0)
    , pose_rot_z(0.0)
    , gaze_0_rot_x(0.0)
    , gaze_0_rot_y(0.0)
    , gaze_0_rot_z(0.0)
    , gaze_1_rot_x(0.0)
    , gaze_1_rot_y(0.0)
    , gaze_1_rot_z(0.0)
    , diff_gaze_x(0.0)
    , diff_gaze_y(0.0)
    , diff_gaze_z(0.0)
    , id_model(0)  {
  (void)_alloc;
    }



   typedef double _pose_tra_x_type;
  _pose_tra_x_type pose_tra_x;

   typedef double _pose_tra_y_type;
  _pose_tra_y_type pose_tra_y;

   typedef double _pose_tra_z_type;
  _pose_tra_z_type pose_tra_z;

   typedef double _pose_rot_x_type;
  _pose_rot_x_type pose_rot_x;

   typedef double _pose_rot_y_type;
  _pose_rot_y_type pose_rot_y;

   typedef double _pose_rot_z_type;
  _pose_rot_z_type pose_rot_z;

   typedef double _gaze_0_rot_x_type;
  _gaze_0_rot_x_type gaze_0_rot_x;

   typedef double _gaze_0_rot_y_type;
  _gaze_0_rot_y_type gaze_0_rot_y;

   typedef double _gaze_0_rot_z_type;
  _gaze_0_rot_z_type gaze_0_rot_z;

   typedef double _gaze_1_rot_x_type;
  _gaze_1_rot_x_type gaze_1_rot_x;

   typedef double _gaze_1_rot_y_type;
  _gaze_1_rot_y_type gaze_1_rot_y;

   typedef double _gaze_1_rot_z_type;
  _gaze_1_rot_z_type gaze_1_rot_z;

   typedef double _diff_gaze_x_type;
  _diff_gaze_x_type diff_gaze_x;

   typedef double _diff_gaze_y_type;
  _diff_gaze_y_type diff_gaze_y;

   typedef double _diff_gaze_z_type;
  _diff_gaze_z_type diff_gaze_z;

   typedef int64_t _id_model_type;
  _id_model_type id_model;




  typedef boost::shared_ptr< ::OpenFace::My_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::OpenFace::My_message_<ContainerAllocator> const> ConstPtr;

}; // struct My_message_

typedef ::OpenFace::My_message_<std::allocator<void> > My_message;

typedef boost::shared_ptr< ::OpenFace::My_message > My_messagePtr;
typedef boost::shared_ptr< ::OpenFace::My_message const> My_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::OpenFace::My_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::OpenFace::My_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace OpenFace

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'OpenFace': ['/home/jorgematos/image_transport_ws/src/OpenFace/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::OpenFace::My_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::OpenFace::My_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::OpenFace::My_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::OpenFace::My_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::OpenFace::My_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::OpenFace::My_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::OpenFace::My_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaefa0165f2d618047dc9a1f3aa528e7";
  }

  static const char* value(const ::OpenFace::My_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaefa0165f2d6180ULL;
  static const uint64_t static_value2 = 0x47dc9a1f3aa528e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::OpenFace::My_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "OpenFace/My_message";
  }

  static const char* value(const ::OpenFace::My_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::OpenFace::My_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pose_tra_x\n\
float64 pose_tra_y\n\
float64 pose_tra_z\n\
float64 pose_rot_x\n\
float64 pose_rot_y\n\
float64 pose_rot_z\n\
float64 gaze_0_rot_x\n\
float64 gaze_0_rot_y\n\
float64 gaze_0_rot_z\n\
float64 gaze_1_rot_x\n\
float64 gaze_1_rot_y\n\
float64 gaze_1_rot_z\n\
float64 diff_gaze_x\n\
float64 diff_gaze_y\n\
float64 diff_gaze_z\n\
int64 id_model\n\
";
  }

  static const char* value(const ::OpenFace::My_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::OpenFace::My_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_tra_x);
      stream.next(m.pose_tra_y);
      stream.next(m.pose_tra_z);
      stream.next(m.pose_rot_x);
      stream.next(m.pose_rot_y);
      stream.next(m.pose_rot_z);
      stream.next(m.gaze_0_rot_x);
      stream.next(m.gaze_0_rot_y);
      stream.next(m.gaze_0_rot_z);
      stream.next(m.gaze_1_rot_x);
      stream.next(m.gaze_1_rot_y);
      stream.next(m.gaze_1_rot_z);
      stream.next(m.diff_gaze_x);
      stream.next(m.diff_gaze_y);
      stream.next(m.diff_gaze_z);
      stream.next(m.id_model);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct My_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::OpenFace::My_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::OpenFace::My_message_<ContainerAllocator>& v)
  {
    s << indent << "pose_tra_x: ";
    Printer<double>::stream(s, indent + "  ", v.pose_tra_x);
    s << indent << "pose_tra_y: ";
    Printer<double>::stream(s, indent + "  ", v.pose_tra_y);
    s << indent << "pose_tra_z: ";
    Printer<double>::stream(s, indent + "  ", v.pose_tra_z);
    s << indent << "pose_rot_x: ";
    Printer<double>::stream(s, indent + "  ", v.pose_rot_x);
    s << indent << "pose_rot_y: ";
    Printer<double>::stream(s, indent + "  ", v.pose_rot_y);
    s << indent << "pose_rot_z: ";
    Printer<double>::stream(s, indent + "  ", v.pose_rot_z);
    s << indent << "gaze_0_rot_x: ";
    Printer<double>::stream(s, indent + "  ", v.gaze_0_rot_x);
    s << indent << "gaze_0_rot_y: ";
    Printer<double>::stream(s, indent + "  ", v.gaze_0_rot_y);
    s << indent << "gaze_0_rot_z: ";
    Printer<double>::stream(s, indent + "  ", v.gaze_0_rot_z);
    s << indent << "gaze_1_rot_x: ";
    Printer<double>::stream(s, indent + "  ", v.gaze_1_rot_x);
    s << indent << "gaze_1_rot_y: ";
    Printer<double>::stream(s, indent + "  ", v.gaze_1_rot_y);
    s << indent << "gaze_1_rot_z: ";
    Printer<double>::stream(s, indent + "  ", v.gaze_1_rot_z);
    s << indent << "diff_gaze_x: ";
    Printer<double>::stream(s, indent + "  ", v.diff_gaze_x);
    s << indent << "diff_gaze_y: ";
    Printer<double>::stream(s, indent + "  ", v.diff_gaze_y);
    s << indent << "diff_gaze_z: ";
    Printer<double>::stream(s, indent + "  ", v.diff_gaze_z);
    s << indent << "id_model: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id_model);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENFACE_MESSAGE_MY_MESSAGE_H
