// Generated by gencpp from file OpenFace/pose_message_all.msg
// DO NOT EDIT!


#ifndef OPENFACE_MESSAGE_POSE_MESSAGE_ALL_H
#define OPENFACE_MESSAGE_POSE_MESSAGE_ALL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <OpenFace/My_message.h>

namespace OpenFace
{
template <class ContainerAllocator>
struct pose_message_all_
{
  typedef pose_message_all_<ContainerAllocator> Type;

  pose_message_all_()
    : person()
    , total_models(0)  {
    }
  pose_message_all_(const ContainerAllocator& _alloc)
    : person(_alloc)
    , total_models(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::OpenFace::My_message_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::OpenFace::My_message_<ContainerAllocator> >::other >  _person_type;
  _person_type person;

   typedef int64_t _total_models_type;
  _total_models_type total_models;




  typedef boost::shared_ptr< ::OpenFace::pose_message_all_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::OpenFace::pose_message_all_<ContainerAllocator> const> ConstPtr;

}; // struct pose_message_all_

typedef ::OpenFace::pose_message_all_<std::allocator<void> > pose_message_all;

typedef boost::shared_ptr< ::OpenFace::pose_message_all > pose_message_allPtr;
typedef boost::shared_ptr< ::OpenFace::pose_message_all const> pose_message_allConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::OpenFace::pose_message_all_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::OpenFace::pose_message_all_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace OpenFace

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'OpenFace': ['/home/jorgematos/image_transport_ws/src/OpenFace/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::OpenFace::pose_message_all_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::OpenFace::pose_message_all_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::OpenFace::pose_message_all_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::OpenFace::pose_message_all_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::OpenFace::pose_message_all_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::OpenFace::pose_message_all_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::OpenFace::pose_message_all_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c482323fdb463d20f58a3cfde1a5056";
  }

  static const char* value(const ::OpenFace::pose_message_all_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c482323fdb463d2ULL;
  static const uint64_t static_value2 = 0x0f58a3cfde1a5056ULL;
};

template<class ContainerAllocator>
struct DataType< ::OpenFace::pose_message_all_<ContainerAllocator> >
{
  static const char* value()
  {
    return "OpenFace/pose_message_all";
  }

  static const char* value(const ::OpenFace::pose_message_all_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::OpenFace::pose_message_all_<ContainerAllocator> >
{
  static const char* value()
  {
    return "My_message[]  person\n\
int64 total_models\n\
\n\
\n\
================================================================================\n\
MSG: OpenFace/My_message\n\
float64 pose_tra_x\n\
float64 pose_tra_y\n\
float64 pose_tra_z\n\
float64 pose_rot_x\n\
float64 pose_rot_y\n\
float64 pose_rot_z\n\
float64 gaze_0_rot_x\n\
float64 gaze_0_rot_y\n\
float64 gaze_0_rot_z\n\
float64 gaze_1_rot_x\n\
float64 gaze_1_rot_y\n\
float64 gaze_1_rot_z\n\
float64 diff_gaze_x\n\
float64 diff_gaze_y\n\
float64 diff_gaze_z\n\
int64 id_model\n\
";
  }

  static const char* value(const ::OpenFace::pose_message_all_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::OpenFace::pose_message_all_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.person);
      stream.next(m.total_models);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_message_all_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::OpenFace::pose_message_all_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::OpenFace::pose_message_all_<ContainerAllocator>& v)
  {
    s << indent << "person[]" << std::endl;
    for (size_t i = 0; i < v.person.size(); ++i)
    {
      s << indent << "  person[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::OpenFace::My_message_<ContainerAllocator> >::stream(s, indent + "    ", v.person[i]);
    }
    s << indent << "total_models: ";
    Printer<int64_t>::stream(s, indent + "  ", v.total_models);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENFACE_MESSAGE_POSE_MESSAGE_ALL_H
