# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from OpenFace/intent_msg_all.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import OpenFace.msg

class intent_msg_all(genpy.Message):
  _md5sum = "c261ae83801d8c2fb6cb2ae1d4bc8c81"
  _type = "OpenFace/intent_msg_all"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """intent_msg[]  intent_person
int64 total_models

================================================================================
MSG: OpenFace/intent_msg
float64 pose_tra_x
float64 pose_tra_y
float64 pose_tra_z
float64 looking
float64 gesture
bool result_interact
float64 box_h
float64 box_w
float64 box_x
float64 box_y
int64 id_model

"""
  __slots__ = ['intent_person','total_models']
  _slot_types = ['OpenFace/intent_msg[]','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       intent_person,total_models

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(intent_msg_all, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.intent_person is None:
        self.intent_person = []
      if self.total_models is None:
        self.total_models = 0
    else:
      self.intent_person = []
      self.total_models = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.intent_person)
      buff.write(_struct_I.pack(length))
      for val1 in self.intent_person:
        _x = val1
        buff.write(_struct_5dB4dq.pack(_x.pose_tra_x, _x.pose_tra_y, _x.pose_tra_z, _x.looking, _x.gesture, _x.result_interact, _x.box_h, _x.box_w, _x.box_x, _x.box_y, _x.id_model))
      buff.write(_struct_q.pack(self.total_models))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.intent_person is None:
        self.intent_person = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.intent_person = []
      for i in range(0, length):
        val1 = OpenFace.msg.intent_msg()
        _x = val1
        start = end
        end += 81
        (_x.pose_tra_x, _x.pose_tra_y, _x.pose_tra_z, _x.looking, _x.gesture, _x.result_interact, _x.box_h, _x.box_w, _x.box_x, _x.box_y, _x.id_model,) = _struct_5dB4dq.unpack(str[start:end])
        val1.result_interact = bool(val1.result_interact)
        self.intent_person.append(val1)
      start = end
      end += 8
      (self.total_models,) = _struct_q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.intent_person)
      buff.write(_struct_I.pack(length))
      for val1 in self.intent_person:
        _x = val1
        buff.write(_struct_5dB4dq.pack(_x.pose_tra_x, _x.pose_tra_y, _x.pose_tra_z, _x.looking, _x.gesture, _x.result_interact, _x.box_h, _x.box_w, _x.box_x, _x.box_y, _x.id_model))
      buff.write(_struct_q.pack(self.total_models))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.intent_person is None:
        self.intent_person = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.intent_person = []
      for i in range(0, length):
        val1 = OpenFace.msg.intent_msg()
        _x = val1
        start = end
        end += 81
        (_x.pose_tra_x, _x.pose_tra_y, _x.pose_tra_z, _x.looking, _x.gesture, _x.result_interact, _x.box_h, _x.box_w, _x.box_x, _x.box_y, _x.id_model,) = _struct_5dB4dq.unpack(str[start:end])
        val1.result_interact = bool(val1.result_interact)
        self.intent_person.append(val1)
      start = end
      end += 8
      (self.total_models,) = _struct_q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_q = struct.Struct("<q")
_struct_5dB4dq = struct.Struct("<5dB4dq")
