# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from OpenFace/My_message.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class My_message(genpy.Message):
  _md5sum = "eaefa0165f2d618047dc9a1f3aa528e7"
  _type = "OpenFace/My_message"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 pose_tra_x
float64 pose_tra_y
float64 pose_tra_z
float64 pose_rot_x
float64 pose_rot_y
float64 pose_rot_z
float64 gaze_0_rot_x
float64 gaze_0_rot_y
float64 gaze_0_rot_z
float64 gaze_1_rot_x
float64 gaze_1_rot_y
float64 gaze_1_rot_z
float64 diff_gaze_x
float64 diff_gaze_y
float64 diff_gaze_z
int64 id_model
"""
  __slots__ = ['pose_tra_x','pose_tra_y','pose_tra_z','pose_rot_x','pose_rot_y','pose_rot_z','gaze_0_rot_x','gaze_0_rot_y','gaze_0_rot_z','gaze_1_rot_x','gaze_1_rot_y','gaze_1_rot_z','diff_gaze_x','diff_gaze_y','diff_gaze_z','id_model']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pose_tra_x,pose_tra_y,pose_tra_z,pose_rot_x,pose_rot_y,pose_rot_z,gaze_0_rot_x,gaze_0_rot_y,gaze_0_rot_z,gaze_1_rot_x,gaze_1_rot_y,gaze_1_rot_z,diff_gaze_x,diff_gaze_y,diff_gaze_z,id_model

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(My_message, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pose_tra_x is None:
        self.pose_tra_x = 0.
      if self.pose_tra_y is None:
        self.pose_tra_y = 0.
      if self.pose_tra_z is None:
        self.pose_tra_z = 0.
      if self.pose_rot_x is None:
        self.pose_rot_x = 0.
      if self.pose_rot_y is None:
        self.pose_rot_y = 0.
      if self.pose_rot_z is None:
        self.pose_rot_z = 0.
      if self.gaze_0_rot_x is None:
        self.gaze_0_rot_x = 0.
      if self.gaze_0_rot_y is None:
        self.gaze_0_rot_y = 0.
      if self.gaze_0_rot_z is None:
        self.gaze_0_rot_z = 0.
      if self.gaze_1_rot_x is None:
        self.gaze_1_rot_x = 0.
      if self.gaze_1_rot_y is None:
        self.gaze_1_rot_y = 0.
      if self.gaze_1_rot_z is None:
        self.gaze_1_rot_z = 0.
      if self.diff_gaze_x is None:
        self.diff_gaze_x = 0.
      if self.diff_gaze_y is None:
        self.diff_gaze_y = 0.
      if self.diff_gaze_z is None:
        self.diff_gaze_z = 0.
      if self.id_model is None:
        self.id_model = 0
    else:
      self.pose_tra_x = 0.
      self.pose_tra_y = 0.
      self.pose_tra_z = 0.
      self.pose_rot_x = 0.
      self.pose_rot_y = 0.
      self.pose_rot_z = 0.
      self.gaze_0_rot_x = 0.
      self.gaze_0_rot_y = 0.
      self.gaze_0_rot_z = 0.
      self.gaze_1_rot_x = 0.
      self.gaze_1_rot_y = 0.
      self.gaze_1_rot_z = 0.
      self.diff_gaze_x = 0.
      self.diff_gaze_y = 0.
      self.diff_gaze_z = 0.
      self.id_model = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_15dq.pack(_x.pose_tra_x, _x.pose_tra_y, _x.pose_tra_z, _x.pose_rot_x, _x.pose_rot_y, _x.pose_rot_z, _x.gaze_0_rot_x, _x.gaze_0_rot_y, _x.gaze_0_rot_z, _x.gaze_1_rot_x, _x.gaze_1_rot_y, _x.gaze_1_rot_z, _x.diff_gaze_x, _x.diff_gaze_y, _x.diff_gaze_z, _x.id_model))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 128
      (_x.pose_tra_x, _x.pose_tra_y, _x.pose_tra_z, _x.pose_rot_x, _x.pose_rot_y, _x.pose_rot_z, _x.gaze_0_rot_x, _x.gaze_0_rot_y, _x.gaze_0_rot_z, _x.gaze_1_rot_x, _x.gaze_1_rot_y, _x.gaze_1_rot_z, _x.diff_gaze_x, _x.diff_gaze_y, _x.diff_gaze_z, _x.id_model,) = _struct_15dq.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_15dq.pack(_x.pose_tra_x, _x.pose_tra_y, _x.pose_tra_z, _x.pose_rot_x, _x.pose_rot_y, _x.pose_rot_z, _x.gaze_0_rot_x, _x.gaze_0_rot_y, _x.gaze_0_rot_z, _x.gaze_1_rot_x, _x.gaze_1_rot_y, _x.gaze_1_rot_z, _x.diff_gaze_x, _x.diff_gaze_y, _x.diff_gaze_z, _x.id_model))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 128
      (_x.pose_tra_x, _x.pose_tra_y, _x.pose_tra_z, _x.pose_rot_x, _x.pose_rot_y, _x.pose_rot_z, _x.gaze_0_rot_x, _x.gaze_0_rot_y, _x.gaze_0_rot_z, _x.gaze_1_rot_x, _x.gaze_1_rot_y, _x.gaze_1_rot_z, _x.diff_gaze_x, _x.diff_gaze_y, _x.diff_gaze_z, _x.id_model,) = _struct_15dq.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_15dq = struct.Struct("<15dq")
