(cl:in-package OpenFace-msg)
(cl:export '(POSE_TRA_X-VAL
          POSE_TRA_X
          POSE_TRA_Y-VAL
          POSE_TRA_Y
          POSE_TRA_Z-VAL
          POSE_TRA_Z
          POSE_ROT_X-VAL
          POSE_ROT_X
          POSE_ROT_Y-VAL
          POSE_ROT_Y
          POSE_ROT_Z-VAL
          POSE_ROT_Z
          GAZE_0_ROT_X-VAL
          GAZE_0_ROT_X
          GAZE_0_ROT_Y-VAL
          GAZE_0_ROT_Y
          GAZE_0_ROT_Z-VAL
          GAZE_0_ROT_Z
          GAZE_1_ROT_X-VAL
          GAZE_1_ROT_X
          GAZE_1_ROT_Y-VAL
          GAZE_1_ROT_Y
          GAZE_1_ROT_Z-VAL
          GAZE_1_ROT_Z
          DIFF_GAZE_X-VAL
          DIFF_GAZE_X
          DIFF_GAZE_Y-VAL
          DIFF_GAZE_Y
          DIFF_GAZE_Z-VAL
          DIFF_GAZE_Z
          ID_MODEL-VAL
          ID_MODEL
))